# site properties and page defaults
title: OpenAGCI Team
subtitle: Shanghai AI Laboratory
description: We are a passionate group of researchers dedicated to exploring the exciting pathway toward achieving Artificial General Intelligence (AGI) through the power of Multi-agent Systems (MAS). Based at the Shanghai AI Laboratory, our team is made up of enthusiastic minds, including experienced researchers, postgraduates, and undergraduates, all working together to push the boundaries of AI research.
header: images/background.png
footer: images/background.png
proofer: false

# site social media and other links
links:
  email: contact@xxyQwQ.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: xxyQwQ
  twitter: xxyQwQ
  youtube: xxyQwQ

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
