- id: arXiv:2409.01392
  type: paper
  description: Propose a benchmark for LLM-based agents to autonomously design collaborative AI systems in ComfyUI, along with a well-performing multi-agent framework to solve the tasks.
  image: images/publications/comfybench.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/2409.01392
    - type: website
      link: https://xxyqwq.github.io/ComfyBench
    - type: source
      link: https://github.com/xxyQwQ/ComfyBench
